version: '3'

networks:
  web:
    external: true
  internal:
    external: false

services:

  db:
    image: mysql:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    #ports:
    #  - ${IP}:3306:3306 # change ip if required
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    networks:
      - internal
    labels:
      - traefik.enable=false
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    restart: always

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - ${IP}:8080:80
    networks:
      - internal
      - web
    labels:
      - traefik.backend=pma
      - traefik.frontend.rule=Host:phpmyadmin.myserver.com
      - traefik.docker.network=web
      - traefik.port=80
    links:
      - db:db
    restart: always

volumes:
  db_data:
